apiVersion: v1
kind: Pod
metadata:
  name: with-volume
spec:
  containers:
    - name: box
      image: busybox:1.38.0
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
